### PR TITLE
add Persian Readme 

### PR DESCRIPTION
**Pull request by DanielBlackBeard**
Hi, because Iran has severe internet censorship. I translated this part into Farsi so that people who are there can use it.
Thanks

### CODE REVIEW

**Comment by Misaka-blog** [comment]
Does Iran gov block 443 port already?

**Comment by DanielBlackBeard** [comment]
I did not test recently to see if this port is closed in the whole Internet, but it is closed in some ISPs and VPS(that bought from Iranian provider).

**Comment by DanielBlackBeard** [comment]
Is there any problem to merge it to your project to solve it?

**Comment by sepehrrostami** [comment]
> Does Iran gov block the 443 port already?

443 is working. But there is much interference on TLS handshake

**Comment by DanielBlackBeard** [comment]
thanks

**Pull request merged**
